### ISSUE TITLE
[BUG] Model not found, but is in the weight folder.

### ISSUE THREAD

**Issue by Jumaron** [TencentARC/AnimeSR#7]
Hey guys,

i encountered a big while installing where the program tells me that the Model was not found in the weight Folder.
But it is in the weight Folder, already tried reinstalling and so on.

![Error2](https://user-images.githubusercontent.com/41344875/209051264-449f4d9f-7f4c-462f-991a-94d3ce96e30a.png)

Above the console log.

Thanks for any help in advance!

**Comment by ToTheBeginning** [comment]
This is not because the Model was not found, it seems to be because some commands in the [script](https://github.com/TencentARC/AnimeSR/blob/main/scripts/inference_animesr_video.py) are not compatible with Windows. Based on what I searched on [stackoverflow](https://stackoverflow.com/questions/3022013/windows-cant-find-the-file-on-subprocess-call), the following are possible solutions.

First make sure you have installed ffmpeg correctly, and then modify the code on line 326 of the [script](https://github.com/TencentARC/AnimeSR/blob/main/scripts/inference_animesr_video.py#L326) to `subprocess.call(' '.join(cmd), shell=True)`.

**Comment by Jumaron** [comment]
I misstyped the path of ffmpeg on the environment table, that fixed it thanks a lot!
